- Andet program end ableton live (gratis????)
- It is worth noting that while the _Suite_ version of Live has been used during development and testing, the _Intro_ version should be sufficient, since it supports up to 16 tracks and full MIDI capabilities @ableton_buy_nodate.
- Uddyb og diskuter testmetoder