= Discussion
Despite developing a functional prototype, enabling testing with the target group, several areas for improvement became evident, suggesting avenues for future refinement to gain a more accurate understanding of its impact (Requirement 11, @table:usabilityRequirements).

Key technical and usability enhancements were identified. The chosen display's loading time, which temporarily disabled controller functionality, highlighted the need for a more responsive display to ensure a smoother Plug'N'Play experience and better feedback (Requirement 4 & 6, @table:usabilityRequirements & Requirement 8, @table:technicalRequirements). Furthermore, underdeveloped hardware features like automatic NFC card detection, if fully realized, could free up the last Controller button for sound interaction, thereby enhancing intuitiveness (Requirement 4, @table:usabilityRequirements). Another key design decision related to musical interaction concerned beat consistency (Requirement 7, @table:usabilityRequirements): while quantization of beats was removed as it did not result in a good "feel" for the user, the pre-defined harmonizing notes were retained to ensure musical cohesion. Future research could explore whether beat quantization could be re-implemented in a manner that still provides a desirable musical "feel" while maintaining rhythmic structure.

While the redesigned lid improved the product's playful, non-intimidating appearance (Requirement 9, @table:usabilityRequirements), the prototype lacked comprehensive user feedback mechanisms. Expanding the display's functionality to provide real-time feedback from buttons and potentiometers would significantly improve usability. Integrating more visual cues directly onto NFC cards, as an alternative to text-labels, would also be beneficial for clarity, ease of use and engagement (Requirement 11, @table:usabilityRequirements). A consistent and strong request from all testers was the addition of LEDs for feedback or decoration, highlighting their importance for a better user experience and to meet clear user preferences.

Cost-effectiveness was a crucial usability goal (Requirement 5, @table:usabilityRequirements). The latest prototype, due to its components and reliance on existing external hardware, maintains a subjectively reasonable price point (@app:bom). However, exploring alternatives to the full Live _Suite_ edition, such as GarageBand on iPad/iPhone (if users already own these devices) or Live _Intro_ edition, could significantly reduce software costs while maintaining sufficient functionality. Conversely, integrating an internal computer and built-in speakers into the prototype, rather than relying on an MCU, the Host, and an external computer, could simplify setup and enhance portability (Requirement 2, @table:usabilityRequirements); this would, however, substantially increase the overall product cost.

Despite the initial requirement for wireless functionality (Requirement 4, @table:technicalRequirements), latency issues during development led to a pivot towards a wired connection for the final prototype. This decision prioritized a stable and responsive user experience over wireless flexibility. Future development should focus on mitigating the practical downsides of the wired connection, such as cable management or potential limitations in movement, while preserving the established stability and low latency (Requirement 9, @table:technicalRequirements). Lastly, improving the method of securing the lid to the chassis, perhaps by exploring alternative fastening mechanisms beyond a magnetic solution, would contribute to the product's overall robustness and user satisfaction.

The evaluation methodology, while yielding useful feedback, had limitations. Time constraints on participant availability may have influenced the depth of interview responses. Future evaluations could benefit from allowing users to explore the product independently or with a peer in a distraction-free environment. This would particularly allow for deeper investigation into cooperative play (Requirement 1, @table:usabilityRequirements), which, despite its apparent significance for fostering engagement and intrinsic motivation, was only briefly explored in one test (@sec:sprint5test) and thus warrants more extensive research. Observing long-term engagement by lending prototypes to users could also provide valuable insights into sustained interest and potential to encourage learning real instruments, though this was infeasible within the project's timeframe. Additionally, the Host, an integral part of the product's functionality, was only internally tested; future iterations should involve external testers.

These identified areas for refinement and future exploration, collectively point towards a promising trajectory for further developing tangible interfaces in music creation.